/*
  # Insert Initial City Data

  Populate the cities table with 50 cities across various continents
  Each city includes 3 hints and 4 multiple choice options
*/

INSERT INTO cities (name, country, continent, hints, choices, difficulty_level)
VALUES
('Paris', 'France', 'Europe', '["City of Light", "Home to the Eiffel Tower", "Known for romance and art"]', '["London", "Paris", "Berlin", "Madrid"]', 1),
('Tokyo', 'Japan', 'Asia', '["Largest metro area in the world", "Famous for neon lights", "Land of rising sun"]', '["Seoul", "Beijing", "Tokyo", "Bangkok"]', 1),
('New York', 'United States', 'North America', '["The Big Apple", "City that never sleeps", "Home of Statue of Liberty"]', '["Los Angeles", "Chicago", "New York", "Boston"]', 1),
('London', 'United Kingdom', 'Europe', '["Home to Big Ben", "City on the Thames", "Royal palaces and museums"]', '["Paris", "London", "Dublin", "Amsterdam"]', 1),
('Sydney', 'Australia', 'Oceania', '["Opera House city", "Harbor views", "Summer in December"]', '["Melbourne", "Sydney", "Brisbane", "Perth"]', 1),
('Barcelona', 'Spain', 'Europe', '["Sagrada Familia basilica", "Gaudí architecture", "Mediterranean coastal city"]', '["Madrid", "Barcelona", "Valencia", "Seville"]', 1),
('Dubai', 'United Arab Emirates', 'Asia', '["Tallest building Burj Khalifa", "Desert luxury city", "Man-made islands"]', '["Abu Dhabi", "Dubai", "Doha", "Riyadh"]', 2),
('Rome', 'Italy', 'Europe', '["Eternal City", "Home to Colosseum", "Vatican located here"]', '["Venice", "Rome", "Florence", "Milan"]', 1),
('Bangkok', 'Thailand', 'Asia', '["Golden temples", "Street food capital", "Floating markets"]', '["Phuket", "Bangkok", "Chiang Mai", "Pattaya"]', 2),
('Venice', 'Italy', 'Europe', '["City of canals", "Grand Canal", "Famous for gondolas"]', '["Venice", "Verona", "Milan", "Florence"]', 2),
('Amsterdam', 'Netherlands', 'Europe', '["City of canals", "Cycling capital", "Anne Frank house"]', '["Rotterdam", "Amsterdam", "Utrecht", "Groningen"]', 1),
('Cairo', 'Egypt', 'Africa', '["Gateway to Ancient Egypt", "Pyramids nearby", "Nile River city"]', '["Alexandria", "Cairo", "Giza", "Luxor"]', 2),
('Berlin', 'Germany', 'Europe', '["Divided city history", "Brandenburg Gate", "Museum Island"]', '["Munich", "Berlin", "Hamburg", "Cologne"]', 1),
('Istanbul', 'Turkey', 'Asia', '["Bridge between continents", "Blue Mosque", "Grand Bazaar"]', '["Ankara", "Istanbul", "Izmir", "Antalya"]', 2),
('Moscow', 'Russia', 'Europe', '["Red Square", "Kremlin fortress", "St. Basil Cathedral"]', '["St. Petersburg", "Moscow", "Kazan", "Sochi"]', 2),
('Singapore', 'Singapore', 'Asia', '["Garden city", "Lion city", "Modern metropolis"]', '["Bangkok", "Singapore", "Kuala Lumpur", "Manila"]', 2),
('Vienna', 'Austria', 'Europe', '["Music city", "Schönbrunn Palace", "Danube River"]', '["Prague", "Vienna", "Budapest", "Ljubljana"]', 2),
('Prague', 'Czech Republic', 'Europe', '["Charles Bridge", "Prague Castle", "Old Town Square"]', '["Warsaw", "Prague", "Bratislava", "Krakow"]', 2),
('Budapest', 'Hungary', 'Europe', '["Thermal baths", "Parliament Building", "Danube beauty"]', '["Vienna", "Budapest", "Prague", "Belgrade"]', 2),
('Mumbai', 'India', 'Asia', '["Gateway of India", "Bollywood city", "Maximum city"]', '["Delhi", "Mumbai", "Bangalore", "Kolkata"]', 2),
('Mexico City', 'Mexico', 'North America', '["Built on island", "Aztec ruins", "Valley of Mexico"]', '["Cancun", "Mexico City", "Guadalajara", "Monterrey"]', 2),
('São Paulo', 'Brazil', 'South America', '["Largest city in Brazil", "Paulista Avenue", "Urban jungle"]', '["Rio de Janeiro", "São Paulo", "Salvador", "Brasília"]', 2),
('Rio de Janeiro', 'Brazil', 'South America', '["Christ the Redeemer", "Copacabana Beach", "Sugarloaf Mountain"]', '["Rio de Janeiro", "São Paulo", "Salvador", "Brasília"]', 1),
('Buenos Aires', 'Argentina', 'South America', '["Tango birthplace", "European feel", "Paris of South America"]', '["Santiago", "Buenos Aires", "Cordoba", "Mendoza"]', 2),
('Reykjavik', 'Iceland', 'Europe', '["Northern Lights", "Hot springs", "Land of fire and ice"]', '["Copenhagen", "Reykjavik", "Stockholm", "Oslo"]', 3),
('Athens', 'Greece', 'Europe', '["Parthenon temple", "Birthplace of democracy", "Ancient ruins"]', '["Rome", "Athens", "Istanbul", "Cairo"]', 2),
('Tel Aviv', 'Israel', 'Asia', '["Modern Middle East", "Mediterranean coast", "Tech hub"]', '["Jerusalem", "Tel Aviv", "Haifa", "Bethlehem"]', 3),
('Marrakech', 'Morocco', 'Africa', '["Red city", "Medina markets", "Atlas Mountains nearby"]', '["Casablanca", "Marrakech", "Fez", "Tangier"]', 3),
('Cape Town', 'South Africa', 'Africa', '["Table Mountain", "Cape of Good Hope", "Mother city"]', '["Johannesburg", "Cape Town", "Durban", "Pretoria"]', 2),
('Seoul', 'South Korea', 'Asia', '["K-pop capital", "Namsan Tower", "Han River city"]', '["Busan", "Seoul", "Incheon", "Daegu"]', 1),
('Hong Kong', 'Hong Kong', 'Asia', '["Victoria Peak", "Neon harbor", "East meets West"]', '["Shanghai", "Hong Kong", "Macau", "Shenzhen"]', 2),
('Shanghai', 'China', 'Asia', '["Oriental Pearl Tower", "The Bund", "Modern metropolis"]', '["Beijing", "Shanghai", "Chongqing", "Guangzhou"]', 2),
('Beijing', 'China', 'Asia', '["Great Wall nearby", "Forbidden City", "Ancient capital"]', '["Shanghai", "Beijing", "Xian", "Chengdu"]', 1),
('Jakarta', 'Indonesia', 'Asia', '["Island capital", "Bustling markets", "Island nation hub"]', '["Surabaya", "Jakarta", "Bandung", "Medan"]', 3),
('Manila', 'Philippines', 'Asia', '["Island city", "Intramuros walled city", "Tropical metropolis"]', '["Cebu", "Manila", "Davao", "Quezon City"]', 3),
('Toronto', 'Canada', 'North America', '["CN Tower", "Diverse culture", "Niagara Falls nearby"]', '["Vancouver", "Toronto", "Calgary", "Montreal"]', 1),
('Vancouver', 'Canada', 'North America', '["Mountains meet ocean", "Stanley Park", "Pacific coast"]', '["Toronto", "Vancouver", "Montreal", "Calgary"]', 1),
('Los Angeles', 'United States', 'North America', '["Hollywood", "Beaches and sunshine", "Entertainment capital"]', '["San Francisco", "Los Angeles", "San Diego", "Las Vegas"]', 1),
('San Francisco', 'United States', 'North America', '["Golden Gate Bridge", "Bay views", "Tech city"]', '["Los Angeles", "San Francisco", "San Diego", "Seattle"]', 1),
('Chicago', 'United States', 'North America', '["Windy City", "Tall buildings", "Lake Michigan"]', '["New York", "Chicago", "Boston", "Washington DC"]', 1),
('Las Vegas', 'United States', 'North America', '["Neon lights", "Casinos and shows", "Desert oasis"]', '["Los Angeles", "Las Vegas", "Phoenix", "Denver"]', 1),
('Miami', 'United States', 'North America', '["Art Deco architecture", "Beaches", "Cuban culture"]', '["Tampa", "Miami", "Orlando", "Key West"]', 2),
('Washington DC', 'United States', 'North America', '["Capitol building", "Political center", "Monument views"]', '["New York", "Washington DC", "Philadelphia", "Boston"]', 2),
('Boston', 'United States', 'North America', '["Historic Freedom Trail", "Harbor", "College town"]', '["New York", "Boston", "Philadelphia", "Washington DC"]', 2),
('Seattle', 'United States', 'North America', '["Space Needle", "Coffee capital", "Rainy city"]', '["San Francisco", "Seattle", "Portland", "Vancouver"]', 2),
('Melbourne', 'Australia', 'Oceania', '["Coffee culture", "Street art alleys", "Cultural hub"]', '["Sydney", "Melbourne", "Brisbane", "Adelaide"]', 2),
('Vienna', 'Austria', 'Europe', '["Imperial palaces", "Music capital", "Danube views"]', '["Prague", "Vienna", "Budapest", "Bratislava"]', 2),
('Lisbon', 'Portugal', 'Europe', '["Seven hills", "Azulejo tiles", "Atlantic coast"]', '["Porto", "Lisbon", "Covilha", "Setúbal"]', 2),
('Barcelona', 'Spain', 'Europe', '["Park Güell", "Gothic Quarter", "Mediterranean beach"]', '["Madrid", "Barcelona", "Seville", "Valencia"]', 1),
('Brussels', 'Belgium', 'Europe', '["Grand Place", "Chocolate capital", "Waffle home"]', '["Amsterdam", "Brussels", "Antwerp", "Bruges"]', 2);
